
#define DEFAULT_FRAME_STYLE "default"
#define DEFAULT_WIDTH 79
#define DEFAULT_HEIGHT 0

// positions inside the style definition array
#define STYLE_EXTRA_WIDTH 0
#define STYLE_EXTRA_HEIGHT 1
#define STYLE_EXTRA_WIDTH_PADDING 2
#define STYLE_EXTRA_HEIGHT_PADDING 3
#define STYLE_LEFT_PAD 4
#define STYLE_RIGHT_PAD 5
#define STYLE_UP_LEFT_CORNER 6
#define STYLE_UP_RIGHT_CORNER 7
#define STYLE_DOWN_RIGHT_CORNER 8
#define STYLE_DOWN_LEFT_CORNER 9
#define STYLE_UP_PAD 10
#define STYLE_DOWN_PAD 11
