
#define ISSUE_ID 0
#define ISSUE_TITLE 1
#define ISSUE_STATUS 2
#define ISSUE_CREATION_TIME 3
#define ISSUE_LAST_TIME 4
#define ISSUE_TIMES 5
#define ISSUE_ORIGINAL_PATHS 6

#define ISSUE_STATUS_OPEN 0
#define ISSUE_STATUS_CLOSED 1
