/* Most names come from the X keyboard configuration file. */

# ifndef _SP_SYMS_H_
# define _SP_SYMS_H_

# define SYM_NULL                0x00

# define SYM_control_a           0x01
# define SYM_control_b           0x02
# define SYM_control_c           0x03
# define SYM_control_d           0x04
# define SYM_control_e           0x05
# define SYM_control_f           0x06

# define SYM_bell                0x07
# define SYM_backspace           0x08
# define SYM_tab                 0x09
# define SYM_linefeed            0x0A
# define SYM_verticaltab         0x0B
# define SYM_formfeed            0x0C
# define SYM_return              0x0D

# define SYM_control_n           0x0E
# define SYM_control_o           0x0F
# define SYM_control_p           0x10
# define SYM_control_q           0x11
# define SYM_control_r           0x12
# define SYM_control_s           0x13
# define SYM_control_t           0x14
# define SYM_control_u           0x15
# define SYM_control_v           0x16
# define SYM_control_w           0x17
# define SYM_control_x           0x18
# define SYM_control_y           0x19
# define SYM_control_z           0x1A
# define SYM_escape              0x1B
# define SYM_undef_1C            0x1C
# define SYM_undef_1D            0x1D
# define SYM_undef_1E            0x1E
# define SYM_undef_1F            0x1F

# define SYM_space               0x20
# define SYM_exclam              0x21
# define SYM_quotedbl            0x22
# define SYM_numbersign          0x23
# define SYM_dollar              0x24
# define SYM_percent             0x25
# define SYM_ampersand           0x26
# define SYM_apostrophe          0x27
# define SYM_parenleft           0x28
# define SYM_parenright          0x29
# define SYM_asterisk            0x2A
# define SYM_plus                0x2B
# define SYM_comma               0x2C
# define SYM_minus               0x2D
# define SYM_period              0x2E
# define SYM_slash               0x2F
# define SYM_0                   0x30
# define SYM_1                   0x31
# define SYM_2                   0x32
# define SYM_3                   0x33
# define SYM_4                   0x34
# define SYM_5                   0x35
# define SYM_6                   0x36
# define SYM_7                   0x37
# define SYM_8                   0x38
# define SYM_9                   0x39
# define SYM_colon               0x3A
# define SYM_semicolon           0x3B
# define SYM_less                0x3C
# define SYM_equal               0x3D
# define SYM_greater             0x3E
# define SYM_question            0x3F
# define SYM_at                  0x40
# define SYM_A                   0x41
# define SYM_B                   0x42
# define SYM_C                   0x43
# define SYM_D                   0x44
# define SYM_E                   0x45
# define SYM_F                   0x46
# define SYM_G                   0x47
# define SYM_H                   0x48
# define SYM_I                   0x49
# define SYM_J                   0x4A
# define SYM_K                   0x4B
# define SYM_L                   0x4C
# define SYM_M                   0x4D
# define SYM_N                   0x4E
# define SYM_O                   0x4F
# define SYM_P                   0x50
# define SYM_Q                   0x51
# define SYM_R                   0x52
# define SYM_S                   0x53
# define SYM_T                   0x54
# define SYM_U                   0x55
# define SYM_V                   0x56
# define SYM_W                   0x57
# define SYM_X                   0x58
# define SYM_Y                   0x59
# define SYM_Z                   0x5A
# define SYM_bracketleft         0x5B
# define SYM_backslash           0x5C
# define SYM_bracketright        0x5D
# define SYM_circumflex          0x5E
# define SYM_underscore          0x5F
# define SYM_grave               0x60
# define SYM_a                   0x61
# define SYM_b                   0x62
# define SYM_c                   0x63
# define SYM_d                   0x64
# define SYM_e                   0x65
# define SYM_f                   0x66
# define SYM_g                   0x67
# define SYM_h                   0x68
# define SYM_i                   0x69
# define SYM_j                   0x6A
# define SYM_k                   0x6B
# define SYM_l                   0x6C
# define SYM_m                   0x6D
# define SYM_n                   0x6E
# define SYM_o                   0x6F
# define SYM_p                   0x70
# define SYM_q                   0x71
# define SYM_r                   0x72
# define SYM_s                   0x73
# define SYM_t                   0x74
# define SYM_u                   0x75
# define SYM_v                   0x76
# define SYM_w                   0x77
# define SYM_x                   0x78
# define SYM_y                   0x79
# define SYM_z                   0x7A
# define SYM_braceleft           0x7B
# define SYM_bar                 0x7C
# define SYM_braceright          0x7D
# define SYM_tilde               0x7E

# define SYM_del                 0x7F

# define SYM_undef_80            0x80
# define SYM_undef_81            0x81
# define SYM_undef_82            0x82
# define SYM_undef_83            0x83
# define SYM_undef_84            0x84
# define SYM_undef_85            0x85
# define SYM_undef_86            0x86
# define SYM_undef_87            0x87
# define SYM_undef_88            0x88
# define SYM_undef_89            0x89
# define SYM_undef_8A            0x8A
# define SYM_undef_8B            0x8B
# define SYM_undef_8C            0x8C
# define SYM_undef_8D            0x8D
# define SYM_undef_8E            0x8E
# define SYM_undef_8F            0x8F
# define SYM_undef_90            0x90
# define SYM_undef_91            0x91
# define SYM_undef_92            0x92
# define SYM_undef_93            0x93
# define SYM_undef_94            0x94
# define SYM_undef_95            0x95
# define SYM_undef_96            0x96
# define SYM_undef_97            0x97
# define SYM_undef_98            0x98
# define SYM_undef_99            0x99
# define SYM_undef_9A            0x9A
# define SYM_undef_9B            0x9B
# define SYM_undef_9C            0x9C
# define SYM_undef_9D            0x9D
# define SYM_undef_9E            0x9E
# define SYM_undef_9F            0x9F

# define SYM_nobreakspace        0xA0
# define SYM_exclamdown          0xA1
# define SYM_cent      	         0xA2
# define SYM_sterling            0xA3
# define SYM_currency            0xA4
# define SYM_yen                 0xA5
# define SYM_brokenbar           0xA6
# define SYM_section             0xA7
# define SYM_diaeresis           0xA8
# define SYM_copyright           0xA9
# define SYM_ordfeminine         0xAA
# define SYM_guillemotleft       0xAB
# define SYM_notsign             0xAC
# define SYM_hyphen              0xAD
# define SYM_registered          0xAE
# define SYM_macron              0xAF
# define SYM_degree              0xB0
# define SYM_plusminus           0xB1
# define SYM_twosuperior         0xB2
# define SYM_threesuperior       0xB3
# define SYM_acute               0xB4
# define SYM_mu                  0xB5
# define SYM_paragraph           0xB6
# define SYM_periodcentered      0xB7
# define SYM_cedilla             0xB8
# define SYM_onesuperior         0xB9
# define SYM_masculine           0xBA
# define SYM_guillemotright      0xBB
# define SYM_onequarter          0xBC
# define SYM_onehalf             0xBD
# define SYM_threequarters       0xBE
# define SYM_questiondown        0xBF
# define SYM_Agrave              0xC0
# define SYM_Aacute              0xC1
# define SYM_Acircumflex         0xC2
# define SYM_Atilde              0xC3
# define SYM_Adiaeresis          0xC4
# define SYM_Aring               0xC5
# define SYM_AE                  0xC6
# define SYM_Ccedilla            0xC7
# define SYM_Egrave              0xC8
# define SYM_Eacute              0xC9
# define SYM_Ecircumflex         0xCA
# define SYM_Ediaeresis          0xCB
# define SYM_Igrave              0xCC
# define SYM_Iacute              0xCD
# define SYM_Icircumflex         0xCE
# define SYM_Idiaeresis          0xCF
# define SYM_ETH                 0xD0
# define SYM_Ntilde              0xD1
# define SYM_Ograve              0xD2
# define SYM_Oacute              0xD3
# define SYM_Ocircumflex         0xD4
# define SYM_Otilde              0xD5
# define SYM_Odiaeresis          0xD6
# define SYM_multiply            0xD7
# define SYM_Ooblique            0xD8
# define SYM_Ugrave              0xD9
# define SYM_Uacute              0xDA
# define SYM_Ucircumflex         0xDB
# define SYM_Udiaeresis          0xDC
# define SYM_Yacute              0xDD
# define SYM_THORN               0xDE
# define SYM_ssharp              0xDF
# define SYM_agrave              0xE0
# define SYM_aacute              0xE1
# define SYM_acircumflex         0xE2
# define SYM_atilde              0xE3
# define SYM_adiaeresis          0xE4
# define SYM_aring               0xE5
# define SYM_ae                  0xE6
# define SYM_ccedilla            0xE7
# define SYM_egrave              0xE8
# define SYM_eacute              0xE9
# define SYM_ecircumflex         0xEA
# define SYM_ediaeresis          0xEB
# define SYM_igrave              0xEC
# define SYM_iacute              0xED
# define SYM_icircumflex         0xEE
# define SYM_idiaeresis          0xEF
# define SYM_eth                 0xF0
# define SYM_ntilde              0xF1
# define SYM_ograve              0xF2
# define SYM_oacute              0xF3
# define SYM_ocircumflex         0xF4
# define SYM_otilde              0xF5
# define SYM_odiaeresis          0xF6
# define SYM_division            0xF7
# define SYM_oslash              0xF8
# define SYM_ugrave              0xF9
# define SYM_uacute              0xFA
# define SYM_ucircumflex         0xFB
# define SYM_udiaeresis          0xFC
# define SYM_yacute              0xFD
# define SYM_thorn               0xFE
# define SYM_ydiaeresis          0xFF

# endif
