
// gender

#define _LANG_GENDER_MALE "varón"
#define _LANG_GENDER_FEMALE "mujer"

#define _LANG_GENDER_TITLE_MALE "señor"
#define _LANG_GENDER_TITLE_FEMALE "señora"

#define _LANG_GENDER_OBJECTIVE_MALE "su"
#define _LANG_GENDER_OBJECTIVE_FEMALE "su"
#define _LANG_GENDER_OBJECTIVE_NEUTRAL "su"

#define _LANG_GENDER_POSSESSIVE_FEMALE "su"
#define _LANG_GENDER_POSSESSIVE_MALE "su"
#define _LANG_GENDER_POSSESSIVE_NEUTRAL "su"

#define _LANG_GENDER_PRONOUN_MALE "él"
#define _LANG_GENDER_PRONOUN_FEMALE "ella"
#define _LANG_GENDER_PRONOUN_NEUTRAL "él"

#define _LANG_GENDER_ARTICLE_FEMALE "la"
#define _LANG_GENDER_ARTICLE_MALE "el"
#define _LANG_GENDER_ARTICLE_PLURAL_FEMALE "las"
#define _LANG_GENDER_ARTICLE_PLURAL_MALE "los"
#define _LANG_GENDER_NUMERAL_FEMALE "una"
#define _LANG_GENDER_NUMERAL_MALE "un"
#define _LANG_GENDER_NUMERAL_PLURAL_FEMALE "unas"
#define _LANG_GENDER_NUMERAL_PLURAL_MALE "unos"
#define _LANG_GENDER_VOCAL_FEMALE "a"
#define _LANG_GENDER_VOCAL_MALE "o"
#define _LANG_GENDER_DEMONSTRATIVE_FEMALE "esta"
#define _LANG_GENDER_DEMONSTRATIVE_MALE "este"