
// gender

#define _LANG_GENDER_MALE "male"
#define _LANG_GENDER_FEMALE "female"

#define _LANG_GENDER_TITLE_MALE "mr."
#define _LANG_GENDER_TITLE_FEMALE "mrs."

#define _LANG_GENDER_OBJECTIVE_MALE "his"
#define _LANG_GENDER_OBJECTIVE_FEMALE "her"
#define _LANG_GENDER_OBJECTIVE_NEUTRAL "its"

#define _LANG_GENDER_POSSESSIVE_FEMALE "his"
#define _LANG_GENDER_POSSESSIVE_MALE "her"
#define _LANG_GENDER_POSSESSIVE_NEUTRAL "its"

#define _LANG_GENDER_PRONOUN_MALE "he"
#define _LANG_GENDER_PRONOUN_FEMALE "she"
#define _LANG_GENDER_PRONOUN_NEUTRAL "it"

#define _LANG_GENDER_ARTICLE_FEMALE "the"
#define _LANG_GENDER_ARTICLE_MALE "the"
#define _LANG_GENDER_ARTICLE_PLURAL_FEMALE "the"
#define _LANG_GENDER_ARTICLE_PLURAL_MALE "the"
#define _LANG_GENDER_NUMERAL_FEMALE "a"
#define _LANG_GENDER_NUMERAL_MALE "a"
#define _LANG_GENDER_NUMERAL_PLURAL_FEMALE "some"
#define _LANG_GENDER_NUMERAL_PLURAL_MALE "some"
#define _LANG_GENDER_VOCAL_FEMALE ""
#define _LANG_GENDER_VOCAL_MALE ""
#define _LANG_GENDER_DEMONSTRATIVE_FEMALE "she"
#define _LANG_GENDER_DEMONSTRATIVE_MALE "he"