/*
 * This file defines the error codes passed to unconnected().  It is
 * automatically generated by DGD on startup.
 */

# define CONNECT_FAILURE	0	/* unspecified failure */
# define CONNECT_REFUSED	1	/* connection refused */
# define CONNECT_HOST_UNREACH	2	/* host unreachable */
# define CONNECT_NET_UNREACH	3	/* network unreachable */
# define CONNECT_TIMEOUT	4	/* connection timed out */
