/*
 * This file defines some basic sizes of datatypes and resources.
 * It is automatically generated by DGD on startup.
 */

# define CHAR_BIT		8		/* # bits in character */
# define CHAR_MIN		0		/* min character value */
# define CHAR_MAX		255		/* max character value */

# define INT_MIN		0x80000000	/* -2147483648 */
# define INT_MAX		2147483647	/* max integer value */
