/*
 * This file gives definitions for the value returned by the
 * typeof() kfun.  It is automatically generated by DGD on startup.
 */

# define T_NIL		0
# define T_INT		1
# define T_FLOAT	2
# define T_STRING	3
# define T_OBJECT	4
# define T_ARRAY	5
# define T_MAPPING	6
