/*
 * This file defines the version of each supported kfun.  It is automatically
 * generated by DGD on startup.
 */

# define KF_ACOS		0
# define KF_ALLOCATE		0
# define KF_ALLOCATE_FLOAT		0
# define KF_ALLOCATE_INT		0
# define KF_ASIN		0
# define KF_ASN_ADD		0
# define KF_ASN_AND		0
# define KF_ASN_CMP		0
# define KF_ASN_DIV		0
# define KF_ASN_LSHIFT		0
# define KF_ASN_MOD		0
# define KF_ASN_MULT		0
# define KF_ASN_OR		0
# define KF_ASN_POW		0
# define KF_ASN_RSHIFT		0
# define KF_ASN_SUB		0
# define KF_ASN_XOR		0
# define KF_ATAN		0
# define KF_ATAN2		0
# define KF_BLOCK_INPUT		0
# define KF_CALL_OTHER		0
# define KF_CALL_OUT		0
# define KF_CALL_TOUCH		0
# define KF_CALL_TRACE		0
# define KF_CEIL		0
# define KF_CLONE_OBJECT		0
# define KF_COMPILE_OBJECT		1
# define KF_CONNECT		0
# define KF_COS		0
# define KF_COSH		0
# define KF_CRYPT		0
# define KF_CTIME		0
# define KF_DATAGRAM_CHALLENGE		0
# define KF_DECRYPT		0
# define KF_DESTRUCT_OBJECT		0
# define KF_DUMP_STATE		1
# define KF_EDITOR		0
# define KF_ENCRYPT		0
# define KF_ERROR		0
# define KF_EXP		0
# define KF_EXPLODE		0
# define KF_FABS		0
# define KF_FIND_OBJECT		0
# define KF_FLOOR		0
# define KF_FMOD		0
# define KF_FREXP		0
# define KF_FUNCTION_OBJECT		0
# define KF_GET_DIR		0
# define KF_HASH_CRC16		0
# define KF_HASH_CRC32		0
# define KF_HASH_STRING		0
# define KF_IMPLODE		0
# define KF_LDEXP		0
# define KF_LOG		0
# define KF_LOG10		0
# define KF_MAKE_DIR		0
# define KF_MAP_INDICES		0
# define KF_MAP_SIZEOF		0
# define KF_MAP_VALUES		0
# define KF_MILLITIME		0
# define KF_MODF		0
# define KF_NEW_OBJECT		0
# define KF_OBJECT_NAME		0
# define KF_PARSE_STRING		0
# define KF_POW		0
# define KF_PREVIOUS_OBJECT		0
# define KF_PREVIOUS_PROGRAM		0
# define KF_QUERY_EDITOR		0
# define KF_QUERY_IP_NAME		0
# define KF_QUERY_IP_NUMBER		0
# define KF_RANDOM		0
# define KF_READ_FILE		0
# define KF_REMOVE_CALL_OUT		0
# define KF_REMOVE_DIR		0
# define KF_REMOVE_FILE		0
# define KF_RENAME_FILE		0
# define KF_RESTORE_OBJECT		0
# define KF_SAVE_OBJECT		0
# define KF_SEND_DATAGRAM		0
# define KF_SEND_MESSAGE		0
# define KF_SHUTDOWN		1
# define KF_SIN		0
# define KF_SINH		0
# define KF_SIZEOF		0
# define KF_SQRT		0
# define KF_SSCANF		0
# define KF_STATUS		0
# define KF_STRLEN		0
# define KF_SWAPOUT		0
# define KF_TAN		0
# define KF_TANH		0
# define KF_THIS_OBJECT		0
# define KF_THIS_USER		0
# define KF_TIME		0
# define KF_TYPEOF		0
# define KF_USERS		0
# define KF_WRITE_FILE		0


/*
 * Supported ciphers and hashing algorithms.
 */

# define ENCRYPT_CIPHERS	"DES", "DES key"
# define DECRYPT_CIPHERS	"DES", "DES key"
# define HASH_ALGORITHMS	"MD5", "SHA1", "crypt"
