/*
 * This file describes the fields of the array returned for every stack
 * frame by the call_trace() function.  It is automatically generated by DGD
 * on startup.
 */

# define TRACE_OBJNAME	0	/* name of the object */
# define TRACE_PROGNAME	1	/* name of the object the function is in */
# define TRACE_FUNCTION	2	/* function name */
# define TRACE_LINE	3	/* line number */
# define TRACE_EXTERNAL	4	/* external call flag */
# define TRACE_FIRSTARG	5	/* first argument to function */
