name: Build and Publish to Github Container Registry 

on:
  push:
    branches: [ master ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login onto ghcr
        run: |
          docker login --username maldorne-bot --password ${{ secrets.MALDORNE_BOT_GHCR_TOKEN }} ghcr.io
      - name: Build image
        run: |
          docker build --no-cache . -t ghcr.io/maldorne/hexagon:latest
      - name: Publish image
        run: |
          docker push ghcr.io/maldorne/hexagon:latest
